[package]
name = "ed_balance"
version = "0.1.0"
authors = ["s. galiamov <sgalyamov@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.59"
